# Generated by Django 4.2.1 on 2023-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=50)),
                ('delivery_date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('cyclist_name', models.CharField(max_length=50)),
                ('delivery_adress', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
