# Generated by Django 4.2.3 on 2023-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('review', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
                ('date_of_review', models.DateTimeField()),
                ('cumulative_rating', models.IntegerField()),
            ],
        ),
    ]
