# Generated by Django 4.2.3 on 2023-07-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_avatar', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
