# Generated by Django 3.2.12 on 2023-08-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_vendor_product_vendor_relations'),
        ('my_cart', '0002_mycart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='product_avatar',
            field=models.ImageField(null=True, upload_to='my_cart_images/'),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='products',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
    ]
