# Generated by Django 3.2.12 on 2023-08-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_vendor_product_vendor_relations'),
        ('my_cart', '0009_alter_mycart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='products',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
    ]
