# Generated by Django 4.2.3 on 2023-07-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('my_cart', '0001_initial'),
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart_relations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cart.mycart'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_relations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_relations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
    ]
