# Generated by Django 4.2.3 on 2023-07-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('my_cart', '0002_mycart_products'),
        ('orders', '0002_orders_cart_relations_orders_customer_relations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart_relations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cart.mycart'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_relations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
    ]
